# Generated by Django 4.2.9 on 2024-12-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Men',
        ),
    ]
